MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no

CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no

KEY_OVERRIDE_ENABLE = yes

INTROSPECTION_KEYMAP_C = garrett361.c

DEFERRED_EXEC_ENABLE = yes
