SRC += 3x5_3_track.c
INTROSPECTION_KEYMAP_C = garrett361_wylder_trackball.c

EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
